Python Web/Python Blog System Project/blog_system/authentication/urls.py
from django.urls import path

from . import views

urlpatterns = (
    path('sign-in/', views.SignInView.as_view(), name='sign in'),
    path('sign-up/', views.SignUpView.as_view(), name='sign up'),
    path('sign-out/', views.SignOutView.as_view(), name='sign out'),
)

from .receivers import *

Python Web/Python Blog System Project/blog_system/blogs/urls.py
from django.urls import path

from . import views

urlpatterns = (
    path('', views.BlogsListView.as_view(), name='index'),
    path('<int:pk>/', views.BlogDetailsView.as_view(), name='blog details'),
    path('<int:pk>/<slug:slug>/', views.BlogDetailsView.as_view(), name='blog details'),
    path('create/', views.CreateBlogView.as_view(), name='create blog'),
)

Python Web/Python Blog System Project/blog_system/blogs_api/urls.py
from django.urls import path

from blog_system.blogs_api.views import CreatePostApiView

urlpatterns = (
    path('', CreatePostApiView.as_view(), name='post create api'),
)

Python Web/Python Blog System Project/blog_system/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('blog_system.authentication.urls')),
    path('', include('blog_system.blogs.urls')),
    path('api/blogs/', include('blog_system.blogs_api.urls')),
]

Python Web/Python Blog System Project/blog_system/authentication/models.py
from django.contrib.auth import get_user_model
from django.db import models

UserModel = get_user_model()


class Profile(models.Model):
    display_name = models.CharField(max_length=30)
    user = models.OneToOneField(UserModel, on_delete=models.CASCADE)

Python Web/Python Blog System Project/blog_system/blogs/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.utils.text import slugify

UserModel = get_user_model()


class Blog(models.Model):
    slug = models.SlugField(
        editable=False,
    )
    name = models.CharField(max_length=30)
    description = models.TextField()
    user = models.ForeignKey(UserModel, on_delete=models.CASCADE)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        return super().save(*args, **kwargs)


class Post(models.Model):
    title = models.CharField(max_length=30)
    text = models.TextField()
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE)
    user = models.ForeignKey(UserModel, on_delete=models.CASCADE)


class Comment(models.Model):
    text = models.TextField()
    user = models.ForeignKey(UserModel, on_delete=models.CASCADE)

Python Web/Python Blog System Project/blog_system/common/models.py
from django.db import models


class BlogSystemSettings(models.Model):
    max_blogs_per_user = models.IntegerField(
        default=3
    )

Python Web/Python Blog System Project/blog_system/authentication/forms.py
from django.contrib.auth import forms as auth_forms
from blog_system.common import form_mixins


class SignUpForm(form_mixins.BootstrapFormMixin, auth_forms.UserCreationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.__init_fields__()


class SignInForm(form_mixins.BootstrapFormMixin, auth_forms.AuthenticationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.__init_fields__()

Python Web/Python Blog System Project/blog_system/authentication/views.py
from django.contrib.auth import login
from django.urls import reverse_lazy
from django.views import generic as views
from django.contrib.auth import views as auth_views

from blog_system.authentication.forms import SignUpForm, SignInForm


class SignUpView(views.CreateView):
    form_class = SignUpForm
    template_name = 'auth/signup.html'
    success_url = reverse_lazy('index')

    def form_valid(self, form):
        valid = super().form_valid(form)
        user = form.save()
        login(self.request, user)
        return valid


class SignInView(auth_views.LoginView):
    template_name = 'auth/signin.html'
    form_class = SignInForm


class SignOutView(auth_views.LogoutView):
    next_page = reverse_lazy('index')

Python Web/Python Blog System Project/blog_system/blogs/views.py
from django.shortcuts import redirect
from django.views import generic as views
from django.contrib.auth import mixins as auth_mixins

from blog_system.blogs.models import Blog
from blog_system.common.utils import can_user_create_blogs


class BlogsListView(views.ListView):
    template_name = 'blogs/list.html'
    model = Blog


class BlogDetailsView(views.DetailView):
    template_name = 'blogs/details.html'
    model = Blog

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context['posts'] = self.get_object().post_set.all()

        return context


class CreateBlogView(auth_mixins.LoginRequiredMixin, views.CreateView):
    model = Blog
    template_name = 'blogs/create.html'
    fields = ('name', 'description')

    def dispatch(self, request, *args, **kwargs):
        if not can_user_create_blogs(request.user):
            return redirect('index')
        return super().dispatch(request, *args, **kwargs)

Python Web/Python Blog System Project/blog_system/blogs_api/views.py
from rest_framework import generics as views
from rest_framework import serializers
from rest_framework import permissions
from rest_framework.exceptions import PermissionDenied

from blog_system.blogs.models import Post, Blog


class PostSerializer(serializers.ModelSerializer):
    blog_id = serializers.IntegerField()

    class Meta:
        model = Post
        fields = ('title', 'text', 'blog_id')


class OwnerPermission(permissions.BasePermission):
    def has_permission(self, request, view):
        return request.user.is_authenticated

    def has_object_permission(self, request, view, obj):
        return obj.user == request.user


class CreatePostApiView(views.CreateAPIView):
    serializer_class = PostSerializer
    permission_classes = [permissions.IsAuthenticated]

    def perform_create(self, serializer):
        blog = Blog.objects.get(pk=serializer.validated_data['blog_id'])
        if blog.user_id != self.request.user.id:
            raise PermissionDenied

        serializer.save(user=self.request.user)
        return super().perform_create(serializer)

Python Web/Python Blog System Project/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block site_title %}SoftUni's Blogs{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/js-cookie@rc/dist/js.cookie.min.js"></script>
</head>
<body>
{% include 'partials/header.html' %}
<div class="site-content">
    {% block site_content %}
    {% endblock %}
</div>
{% block scripts_body_end %}
{% endblock %}
</body>
</html>

Python Web/Python Blog System Project/templates/blogs/create.html
{% extends 'base.html' %}

{% block site_title %}Create a blog{% endblock %}

{% block site_content %}
    <form action="" method="post">
        {% csrf_token %}
        {{ form }}
        <button>Create</button>
    </form>
{% endblock %}

Python Web/Python Blog System Project/templates/blogs/details.html
{% extends 'base.html' %}
{% load static %}

{% block site_title %}{{ blog.name }}{% endblock %}

{% block site_content %}
    {{ blog.name }}
    <form id="form-create-post" action="{% url 'post create api' %}" method="post">
        <label>
            Title: <input type="text" name="title">
        </label>
        <label>
            Text: <input type="text" name="text">
        </label>
        <input type="hidden" name="blog_id" value="{{ blog.id }}">
        <button>Create</button>
    </form>
    <ul>
        {% for post in posts %}
            <li>
                {{ post.title }}
            </li>
        {% endfor %}
    </ul>

{% endblock %}

{% block scripts_body_end %}
    <script src="{% static 'js/create_post.js' %}"></script>
{% endblock %}

Python Web/Python Blog System Project/templates/blogs/list.html
{% extends 'base.html' %}

{% load create_blog %}
{% block site_title %}All blogs{% endblock %}

{% block site_content %}
    {% create_blog user %}
    <ul>
        {% for blog in blog_list %}
            <li>
                {{ blog.name }}
                <a href="{% url 'blog details' blog.id blog.slug %}">See blog</a>
            </li>
        {% endfor %}
    </ul>
{% endblock %}

Python Web/Python Blog System Project/templates/partials/create_blog.html
{% if disabled %}
    <a disabled="disabled" class="disabled">Create blog</a>
{% else %}
    <a href="{% url 'create blog' %}">Create blog</a>
{% endif %}

Python Web/Python Blog System Project/templates/partials/header.html
{% load create_blog %}
<header class="site-header">
    <div class="site-content header-wrapper">
        <h1>SoftUni Blogs</h1>
        <nav class="site-nav">
            <ul class="list list-horizontal">
                <li>
                    <a href="{% url 'index' %}">
                        Home
                    </a>
                </li>
                <li>
                    {% create_blog user %}
                </li>
                {% if user.is_authenticated %}
                    <li>
                        <a href="#">{{ user.username }}</a>
                    </li>
                    <li>
                        <a href="{% url 'sign out' %}">Sign out</a>
                    </li>
                {% else %}
                    <li>
                        <a href="{% url 'sign in' %}">Sign in</a>
                    </li>
                    <li>
                        <a href="{% url 'sign up' %}">Sign up</a>
                    </li>
                {% endif %}
            </ul>
        </nav>
    </div>
</header>